# ============================================================
#  SonarQube - Configuración del proyecto
#  Proyecto: PSW Pipeline Base
#  Autor: Dayron Casas
# ============================================================

sonar.projectKey=psw-pipeline-base
sonar.projectName=PSW Pipeline Base
sonar.projectVersion=0.0.1-SNAPSHOT

# Ruta de fuentes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Cobertura JaCoCo
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusiones
sonar.exclusions=**/PswPipelineBaseApplication.java

# Java version
sonar.java.source=21
